import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AddProductButton from "./components/AddProductButton";
import { Metadata } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="page-header">
          <div className="wrapper">
            <div className="heading">
              <h1>Inventory Management</h1>
              <span className="text-gray-500">Manage and track your global product catalogue across all categories</span>
            </div>
            <AddProductButton/>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
